apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liberu-billing-dev

resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: liberu-billing-app
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: liberu-billing-horizon

configMapGenerator:
  - name: liberu-billing-config
    behavior: merge
    literals:
      - APP_ENV=local
      - APP_DEBUG=true
      - LOG_LEVEL=debug

images:
  - name: liberu/billing
    newTag: develop
